services:
  workspace:
    image: object-detection:latest
    build:
      context: .
      dockerfile: docker/object-detection.dockerfile
      args:
        USERNAME: ${USER}
        PASSWORD: ${PASSWORD}
    container_name: object-detection
    shm_size: "8gb"
    gpus: all
    volumes:
      - .:/home/${USER}/applied-ai-workbench/tasks/object-detection
      - /home/${USER}/github/applied-ai-workbench/artifacts:/home/${USER}/applied-ai-workbench/tasks/object-detection/artifacts:ro
    ports:
      - "8000:22"
    restart: always